services:
  frontend-app:
    image : hedilmaaoui/front-session18
    container_name: frontend-app  # Name of the container
    ports:
      - '5000:80' #container port kima n7eb , 80 container port

#parametre mich barcha donc juste commande
#docker run -d -p 5000:80 hedilmaaoui/front-session18
#npuliw image toul 3al vps sans docker compose lfichier hetha