services:
  frontend-app:
    image : hedilmaaoui/front-session18
    container_name: frontend-app  # Name of the container
    environment:
      - VITE_API_URL=https://api.158.lebondeveloppeur.net/  #n7ot url API Backend
    ports:
      - '5000:80' #container port kima n7eb , 80 container port
